const DRAWER_TURNON = "app/duck/DRAWER_TURNON";
const DRAWER_TURNOFF = "app/duck/DRAWER_TURNOFF";

const LOGIN_REQUEST = "app/duck/LOGIN_REQUEST";
const LOGOUT_REQUEST = "app/duck/LOGOUT_REQUEST ";

const LOGIN_FINISH = "app/duck/LOGIN_FINISH";
const LOGOUT_FINISH = "app/duck/LOGOUT_FINISH";

const INVALID_TOKEN = "app/duck/INVALID_TOKEN";

const MSG_RESPONSE = "app/duck/MSG_RESPONSE";
const INSERT_MSG = "app/duck/INSERT_MSG";
const REMOVE_MSG = "app/duck/REMOVE_MSG";


export default {
    DRAWER_TURNON,
    DRAWER_TURNOFF,
    LOGIN_REQUEST,
    LOGOUT_REQUEST,
    LOGIN_FINISH,
    LOGOUT_FINISH,
    INVALID_TOKEN,
    MSG_RESPONSE,
    INSERT_MSG,
    REMOVE_MSG,
};